171648182-story(user role setting): add user role router
STACK-UP-3/champs-backend pull request #22
Opened 2020-04-10 17:42 UTC by YankyJayChris

#### Description
It adds an endpoint that enables "Super administrator" users to assign roles to other users.

#### Type of change

Please select the relevant option

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Others (cosmetics, styling, improvements)
- [ ] This change requires a documentation update

#### How Has This Been Tested?

- [X] Unit
- [ ] Integration
- [ ] End-to-end
- [ ] No testing required

#### How to Test

-clone the repository, run the server locally then follow the instructions from the swagger documentation.

#### Any background context you want to add (Optional)
-N/A

#### STORY ID

[Finishes #171648182]

2020-04-10 18:20 UTC, brianineza01 approved these changes

2020-04-10 18:22 UTC, Irutingabo approved these changes

2020-04-11 08:00 UTC, placideirandora requested changes

2020-04-11 08:00 UTC, placideirandora commented on server/helpers/tokenHelper.js
> +  static generateToken({
Check Brian's PR to see the helper that we have agreed on for generating a token and consider implementing it.

2020-04-11 08:00 UTC, placideirandora commented on server/index.js
> +    message: 'Hey !! You are Welcome to BareFoot Nomad, Use the link below its documentation of application',
Consider updating the message to **You are Welcome to BareFoot Nomad. Use the link below to navigate to the API Documentation.**

2020-04-11 08:00 UTC, placideirandora commented on server/middlewares/tokenValidator.js
> +      return res.status(401).json({ status: 401, error: 'User not recognised. Please create account and try again.' });
Consider updating the comment to  **User not recognised. Please register and try again**.

2020-04-11 16:09 UTC, placideirandora approved these changes

2020-04-11 16:11 UTC, merged