173254779 Password reset response
STACK-UP-3/champs-backend pull request #37
Opened 2020-06-09 22:52 UTC by Agnes-N

#### Description

This PR is for fixing the password reset link page.
 
#### Type of change

Please select the relevant option

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Others (cosmetics, styling, improvements)
- [ ] This change requires a documentation update

#### How Has This Been Tested?

- [X] Unit
- [ ] Integration
- [ ] End-to-end
- [ ] No testing required

#### How to Test
Setup:

 1. Clone this repo on your machine
 2. Add `.env` file by referring to `.env.example`
 3. Go in the `swagger` file and change `host` address to `localhost:3000`
 4. Run `npm i ` to install dependencies
 5. Do `npm run serve` command

Test:

 1. Open your preferred testing tool, I would suggest using your browser
 2. Enter this link in the URL `localhost:3000/api/v1/auth/reset-link` to reset your password.
 3. Enter your email to reset your password.
 4. You will see a toast message to go to your email for a changing your password.

#### Any background context you want to add (Optional)

N/A

#### STORY ID

[Fixes #173254779]

2020-06-15 17:02 UTC, placideirandora requested changes

2020-06-15 17:02 UTC, placideirandora commented on server/controllers/passwordController.js
> +    res.redirect(`https://champs-frontend.herokuapp.com/change?email=${email}&token=${token}`);
Why are you returning the token as well?

2020-06-15 17:02 UTC, placideirandora commented on server/helpers/authHelper.js
> +          <p style="font-family: fantasy;font-size: 20px;">Confirm your email to proceed to Nomad champs</p>
Change **Nomad champs** to **Barefoot Nomad**.

2020-06-15 17:02 UTC, placiderapson commented on server/middleware/user.js
> +          message: 'You should verify your email before you reset it.'
Instead of **it**, put **the password**. Thus, the message will become **You should verify your email before you reset the password**.

2020-06-15 17:02 UTC, placiderapson commented on server/middleware/user.js
> +        message: 'Something went wrong when resetting your password.',
Instead of **when** resetting... Put **while** resetting...

2020-06-15 17:02 UTC, placiderapson commented on server/tests/passwordResetTest.test.js
> +  it('should not send a password reset link email to a user', (done) => {
The message is the same as the below one. Kindly, make a difference.

2020-06-15 17:02 UTC, placiderapson commented on server/tests/passwordResetTest.test.js
> +  it('should not send a password reset link email to a user', (done) => {
The message is the same as the above one. Kindly, make a difference.

2020-06-15 17:15 UTC, Agnes-N commented on server/controllers/passwordController.js
> +    res.redirect(`https://champs-frontend.herokuapp.com/change?email=${email}&token=${token}`);
To be able to get a password reset page....you need to have email and the token in the link!

2020-06-16 11:02 UTC, placideirandora approved these changes

2020-06-16 11:02 UTC, merged