#171648165 Setup Coveralls file
STACK-UP-3/champs-backend pull request #4
Opened 2020-03-24 17:08 UTC by YankyJayChris

#### Description
This PR is for setting up Coveralls code coverage service

#### Type of change

Please select the relevant option

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Others (cosmetics, styling, improvements)
- [ ] This change requires a documentation update

#### How Has This Been Tested?

- [ ] Unit
- [ ] Integration
- [ ] End-to-end
- [x] No testing required

#### How to Test

N/A

#### Any background context you want to add (Optional)

N/A

#### STORY ID

[Finishes #171648165]

2020-03-25 07:59 UTC, brianineza01 approved these changes

2020-03-25 09:05 UTC, Agnes-N approved these changes

2020-03-25 09:34 UTC, Irutingabo approved these changes

2020-03-25 12:28 UTC, deschantkn requested changes
This will not work as we are not using travis pro. That is for paid private repos.
This file is also not necessary as we will use Travis to report coverage. What you need to do is the following:

1. Set up a coverage script in our `package.json` file.
2. Coveralls gives us a coverage badge, you need to add that badge to our `README.md` file

Once that is done @Agnes-N will integrate your coverage command into our `travis.yml` config file since she is the one working on that.

You can reach out if you need more clarification.

2020-03-26 08:53 UTC, deschantkn requested changes
Great job @YankyJayChris ,
The last step is to connect the coverage script to Travis, so coverage can be reported automatically when builds run on Travis. You can do that by editing the `.travis.yml` file and add this:

```
after_success:
  - npm run coveralls
```

This will ensure that coverage is only reported if tests pass successfully.

2020-03-26 08:53 UTC, deschantkn commented on .coveralls.yml
> +service_name: travis-pro
We are not using travis-pro, kindly remove this as it has no effect. Unless you have a reason for it being here, if yes let me know.

2020-03-26 09:20 UTC, deschantkn approved these changes
Looks good

2020-03-26 09:21 UTC, merged